import User from '../models/User.js';
import generateToken from '../utils/generateToken.js';
import sendEmail from '../utils/sendEmail.js';

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
const registerUser = async (req, res) => {
    const { name, email, password, phone, address, slot, role } = req.body;

    try {
        const userExists = await User.findOne({ email: email.toLowerCase() });

        if (userExists) {
            return res.status(400).json({ success: false, message: 'User already exists with this email' });
        }

        let finalPassword = password;
        let autoGenerated = false;

        // Auto-generate password only if password is not specified
        const userRole = role || 'user';
        if (!finalPassword || finalPassword.trim() === '') {
            finalPassword = Math.random().toString(36).slice(-8) + Math.floor(Math.random() * 10);
            autoGenerated = true;
        }

        const user = await User.create({
            name,
            email: email.toLowerCase(),
            password: finalPassword,
            phone: phone || '',
            address: address || '',
            slot: slot || '',
            role: userRole
        });

        if (user) {
            if (autoGenerated) {
                const message = `Welcome to LibraFlow Library!\n\nYour account has been successfully created.\n\nHere are your login credentials:\nEmail: ${email}\nPassword: ${finalPassword}\n\nPlease login at the library website and change your password in your profile tab.\n\nThank you,\nLibraFlow Management`;
                const html = `
                    <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #84C18B; border-radius: 10px; max-width: 600px;">
                        <h2 style="color: #0F4C5C;">Welcome to LibraFlow!</h2>
                        <p>Your library account has been successfully created with the following details:</p>
                        <table style="width: 100%; border-collapse: collapse;">
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Name</b></td>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;">${name}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Email / Username</b></td>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;">${email}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Temporary Password</b></td>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd; color: #E04F5F; font-size: 1.1em; font-weight: bold;">${finalPassword}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;"><b>Chosen Slot</b></td>
                                <td style="padding: 8px; border-bottom: 1px solid #ddd;">${slot || 'None'}</td>
                            </tr>
                        </table>
                        <p style="margin-top: 20px;">Please login at the LibraFlow website using these credentials. You can update your password anytime in your Profile tab.</p>
                        <p style="color: #666; font-size: 0.9em; margin-top: 30px;">Thank you,<br/>LibraFlow Management Team</p>
                    </div>
                `;

                try {
                    await sendEmail({
                        email: email,
                        subject: 'Your LibraFlow Library Credentials',
                        message: message,
                        html: html
                    });
                } catch (emailErr) {
                    console.log('Email delivery skipped/logged:', emailErr.message);
                }
            }

            res.status(201).json({
                success: true,
                message: autoGenerated 
                    ? "Registration successful! Your login credentials have been configured." 
                    : "Registration successful! You can now log in.",
                _id: user._id,
                name: user.name,
                email: user.email,
                role: user.role,
                generatedPassword: autoGenerated ? finalPassword : null,
                token: generateToken(user._id),
            });
        } else {
            res.status(400).json({ success: false, message: 'Invalid user data provided' });
        }
    } catch (error) {
        res.status(500).json({ success: false, message: 'Server Error', error: error.message });
    }
};

// @desc    Auth user & get token
// @route   POST /api/auth/login
// @access  Public
const loginUser = async (req, res) => {
    const { email, password } = req.body;

    try {
        if (!email || !password) {
            return res.status(400).json({ success: false, message: 'Please provide email and password' });
        }

        const normalizedEmail = email.trim().toLowerCase();
        const user = await User.findOne({ email: normalizedEmail });

        if (user && (await user.matchPassword(password))) {
            return res.json({
                success: true,
                data: {
                    _id: user._id,
                    name: user.name,
                    email: user.email,
                    role: user.role,
                    slot: user.slot,
                    membership: user.membership,
                    token: generateToken(user._id)
                },
                message: 'Login successful'
            });
        } else {
            return res.status(401).json({ success: false, message: 'Invalid email or password' });
        }
    } catch (error) {
        console.error('Login error:', error);
        return res.status(500).json({ success: false, message: 'Server error during login', error: error.message });
    }
};

export { registerUser, loginUser };
